 // Source code is unavailable, and was generated by the Fernflower decompiler.
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;

public class LoadXml {
   public List<BoardSpace> loadBoardSpaces() {
      ArrayList var1 = new ArrayList();

      try {
         File var2 = new File("xml/board.xml");
         DocumentBuilderFactory var3 = DocumentBuilderFactory.newInstance();
         DocumentBuilder var4 = var3.newDocumentBuilder();
         Document var5 = var4.parse(var2);
         var5.getDocumentElement().normalize();
         NodeList var6 = var5.getElementsByTagName("set");

         for(int var7 = 0; var7 < var6.getLength(); ++var7) {
            Element var8 = (Element)var6.item(var7);
            String var9 = var8.getAttribute("name");
            NodeList var10 = var8.getElementsByTagName("neighbor");
            String[] var11 = new String[var10.getLength()];

            int var12;
            for(var12 = 0; var12 < var10.getLength(); ++var12) {
               var11[var12] = ((Element)var10.item(var12)).getAttribute("name");
            }

            boolean var21 = false;
            NodeList var13 = var8.getElementsByTagName("take");
            var12 = var13.getLength();
            NodeList var14 = var8.getElementsByTagName("part");
            Role[] var15 = new Role[var14.getLength()];

            for(int var16 = 0; var16 < var14.getLength(); ++var16) {
               Element var17 = (Element)var14.item(var16);
               String var18 = var17.getAttribute("name");
               int var19 = Integer.parseInt(var17.getAttribute("level"));
               var15[var16] = new Role(var18, var19, "Extra");
            }

            BoardSpace var22 = new BoardSpace(var9, "set", var11);
            var1.add(var22);
         }
      } catch (Exception var20) {
         var20.printStackTrace();
      }

      return var1;
   }

   public List<Scene> loadScenes() {
      ArrayList var1 = new ArrayList();

      try {
         File var2 = new File("xml/cards.xml");
         DocumentBuilderFactory var3 = DocumentBuilderFactory.newInstance();
         DocumentBuilder var4 = var3.newDocumentBuilder();
         Document var5 = var4.parse(var2);
         var5.getDocumentElement().normalize();
         NodeList var6 = var5.getElementsByTagName("card");

         for(int var7 = 0; var7 < var6.getLength(); ++var7) {
            Element var8 = (Element)var6.item(var7);
            String var9 = var8.getAttribute("name");
            int var10 = Integer.parseInt(var8.getAttribute("budget"));
            NodeList var11 = var8.getElementsByTagName("scene");
            String var12 = "";
            if (var11.getLength() > 0) {
               Element var13 = (Element)var11.item(0);
               var12 = var13.getAttribute("number");
            }

            NodeList var20 = var8.getElementsByTagName("part");
            Role[] var14 = new Role[var20.getLength()];

            for(int var15 = 0; var15 < var20.getLength(); ++var15) {
               Element var16 = (Element)var20.item(var15);
               String var17 = var16.getAttribute("name");
               int var18 = Integer.parseInt(var16.getAttribute("level"));
               var14[var15] = new Role(var17, var18, "Featured");
            }

            Scene var21 = new Scene(var12, var9, var10, var14);
            var1.add(var21);
         }
      } catch (Exception var19) {
         var19.printStackTrace();
      }

      return var1;
   }

   public void loadGameData(GameBoard var1) {
      List var2 = this.loadBoardSpaces();
      List var3 = this.loadScenes();
      var1.boardSpaces.clear();
      var1.boardSpaces.addAll(var2);
      var1.sceneDeck.clear();
      var1.sceneDeck.addAll(var3);
   }
}




